site_name: GMLIB
repo_url: https://github.com/GroupMountain/GMLIB
nav:
  - GMLIB: "index.md"
  - 开发指南: "develop.md"
  - API接口:
      - C++接口:
          - 事件:
              - "实体事件": "./cpp/event/entity.md"
              - "全局事件": "./cpp/event/Level.md"
              - "玩家事件": "./cpp/event/player.md"
          - "接口": "./cpp/serverapi.md"
      - LSE开发API:
        - "ModAPI": "./lse/mod.md"
        - "虚拟在线玩家API": "./lse/fakelist.md"
theme: material
