site_name: GMLIB
repo_url: https://github.com/GroupMountain/GMLIB
nav:
  - 主页: "index.md"
  - API:
      - CPP开发API:
          - 事件:
              - "实体事件": "./cpp/event/entity.md"
              - "全局事件": "./cpp/event/Level.md"
              - "玩家事件": "./cpp/event/player.md"
          - "接口": "./cpp/serverapi.md"
      - LSE开发API:
        - "ModAPI": "./lse/mod.md"
        - "虚拟在线玩家API": "./lse/fakelist.md"
  - 关于: "About.md"
theme: material
